import type {
  AssetBilling,
  AssetCost,
  AssetGenerationMetadata,
  AssetProvenanceTarget,
  AssetUsage,
  RedactedAssetRequest,
} from "@ludelier/assets";

export const MAX_ASSET_INGRESS_BYTES = 12 * 1024 * 1024;
export const MAX_ASSET_INGRESS_JSON_BYTES = 17 * 1024 * 1024;

/**
 * Prompt- and credential-free data accepted before vendor dispatch. The Vite host keeps the
 * resulting assets-node preflight object server-side and returns an opaque receipt instead.
 */
export interface BrowserAssetPreflightPayload {
  readonly destination: {
    readonly storyId: string;
    readonly assetId: string;
    readonly relativePath: string;
  };
  readonly target: AssetProvenanceTarget;
  readonly request: RedactedAssetRequest;
  readonly requestHash: string;
  readonly promptHash: string;
}

/** Generated bytes can cross only with a server-issued one-use receipt. */
export interface BrowserAssetPersistPayload {
  readonly receipt: string;
  readonly metadata: Pick<
    AssetGenerationMetadata,
    "mimeType" | "extension" | "createdAt" | "usage" | "billing"
  >;
  readonly bytesBase64: string;
}

/**
 * Reject unknown fields so a caller cannot smuggle public/provenance roots, plaintext prompts,
 * credentials, raw provider responses, or path traversal through the development ingress.
 */
export function parseBrowserAssetPreflightPayload(value: unknown): BrowserAssetPreflightPayload | undefined {
  if (
    !isRecord(value) ||
    !hasOnlyKeys(value, ["destination", "target", "request", "requestHash", "promptHash"])
  ) {
    return undefined;
  }
  if (!isRecord(value.destination) || !hasOnlyKeys(value.destination, ["storyId", "assetId", "relativePath"]))
    return undefined;
  const { storyId, assetId, relativePath } = value.destination;
  if (
    typeof storyId !== "string" ||
    typeof assetId !== "string" ||
    typeof relativePath !== "string" ||
    !safeId(storyId) ||
    !safeId(assetId) ||
    !safeRelativePath(relativePath)
  ) {
    return undefined;
  }
  if (typeof value.requestHash !== "string" || !/^[a-f0-9]{64}$/.test(value.requestHash)) return undefined;
  if (typeof value.promptHash !== "string" || !/^[a-f0-9]{64}$/.test(value.promptHash)) return undefined;
  const target = parseTarget(value.target);
  const request = parseRequest(value.request);
  if (
    target === undefined ||
    request === undefined ||
    target.kind !== request.kind ||
    !relativePath.endsWith(`.${request.outputFormat}`)
  ) {
    return undefined;
  }

  return {
    destination: { storyId, assetId, relativePath },
    target,
    request,
    requestHash: value.requestHash,
    promptHash: value.promptHash,
  };
}

/** Receipts have no meaningful client-side structure; the server validates their ownership and TTL. */
export function parseBrowserAssetPersistPayload(value: unknown): BrowserAssetPersistPayload | undefined {
  if (!isRecord(value) || !hasOnlyKeys(value, ["receipt", "metadata", "bytesBase64"])) return undefined;
  if (typeof value.receipt !== "string" || !/^[A-Za-z0-9_-]{24,128}$/.test(value.receipt)) return undefined;
  const metadata = parseMetadata(value.metadata);
  if (
    metadata === undefined ||
    typeof value.bytesBase64 !== "string" ||
    value.bytesBase64.length === 0 ||
    value.bytesBase64.length > MAX_ASSET_INGRESS_JSON_BYTES ||
    !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value.bytesBase64)
  ) {
    return undefined;
  }
  return { receipt: value.receipt, metadata, bytesBase64: value.bytesBase64 };
}

function parseTarget(value: unknown): AssetProvenanceTarget | undefined {
  if (
    !isRecord(value) ||
    !hasOnlyKeys(value, ["providerId", "modelId", "kind", "endpoint"]) ||
    typeof value.modelId !== "string" ||
    typeof value.endpoint !== "string" ||
    !safeModel(value.modelId)
  ) {
    return undefined;
  }
  if (
    value.kind === "image" &&
    (value.providerId === "openai" || value.providerId === "openrouter") &&
    value.endpoint ===
      (value.providerId === "openai"
        ? "https://api.openai.com/v1/images/generations"
        : "https://openrouter.ai/api/v1/images")
  ) {
    return { providerId: value.providerId, modelId: value.modelId, kind: "image", endpoint: value.endpoint };
  }
  if (
    value.kind === "audio" &&
    value.providerId === "openai" &&
    value.endpoint === "https://api.openai.com/v1/audio/speech"
  ) {
    return { providerId: "openai", modelId: value.modelId, kind: "audio", endpoint: value.endpoint };
  }
  return undefined;
}

function parseRequest(value: unknown): RedactedAssetRequest | undefined {
  if (!isRecord(value) || typeof value.kind !== "string") return undefined;
  if (value.kind === "image") {
    if (
      !hasOnlyKeys(value, ["kind", "role", "outputFormat", "parameters"]) ||
      (value.role !== "background" && value.role !== "sprite") ||
      value.outputFormat !== "png" ||
      !isRecord(value.parameters) ||
      Object.keys(value.parameters).some((key) => !["background", "size", "quality"].includes(key)) ||
      (value.parameters.background !== "opaque" && value.parameters.background !== "transparent") ||
      (value.parameters.quality !== undefined &&
        (typeof value.parameters.quality !== "string" || value.parameters.quality.length > 64))
    ) {
      return undefined;
    }
    const size = value.parameters.size;
    let parsedSize: { readonly width: number; readonly height: number } | undefined;
    if (size !== undefined) {
      if (
        !isRecord(size) ||
        !hasOnlyKeys(size, ["width", "height"]) ||
        typeof size.width !== "number" ||
        typeof size.height !== "number" ||
        !Number.isSafeInteger(size.width) ||
        !Number.isSafeInteger(size.height) ||
        size.width < 1 ||
        size.height < 1 ||
        size.width > 4096 ||
        size.height > 4096
      ) {
        return undefined;
      }
      parsedSize = { width: size.width, height: size.height };
    }
    if (value.role === "background" && parsedSize === undefined) return undefined;
    return {
      kind: "image",
      role: value.role,
      outputFormat: "png",
      parameters: {
        background: value.parameters.background,
        ...(parsedSize === undefined ? {} : { size: parsedSize }),
        ...(value.parameters.quality === undefined ? {} : { quality: value.parameters.quality }),
      },
    };
  }

  if (
    !hasOnlyKeys(value, ["kind", "role", "outputFormat", "parameters"]) ||
    value.kind !== "audio" ||
    (value.role !== "music" && value.role !== "sfx" && value.role !== "voice") ||
    value.outputFormat !== "mp3" ||
    !isRecord(value.parameters) ||
    Object.keys(value.parameters).some((key) => !["voice", "speed"].includes(key)) ||
    (value.parameters.voice !== undefined &&
      (typeof value.parameters.voice !== "string" || value.parameters.voice.length > 64)) ||
    (value.parameters.speed !== undefined &&
      (typeof value.parameters.speed !== "number" || !Number.isFinite(value.parameters.speed)))
  ) {
    return undefined;
  }
  return {
    kind: "audio",
    role: value.role,
    outputFormat: "mp3",
    parameters: {
      ...(value.parameters.voice === undefined ? {} : { voice: value.parameters.voice }),
      ...(value.parameters.speed === undefined ? {} : { speed: value.parameters.speed }),
    },
  };
}

function parseMetadata(value: unknown): BrowserAssetPersistPayload["metadata"] | undefined {
  if (
    !isRecord(value) ||
    !hasAllowedKeys(value, ["mimeType", "extension", "createdAt", "usage", "billing"]) ||
    typeof value.mimeType !== "string" ||
    typeof value.extension !== "string" ||
    typeof value.createdAt !== "string" ||
    !Number.isFinite(Date.parse(value.createdAt))
  ) {
    return undefined;
  }
  const usage = value.usage === undefined ? undefined : parseUsage(value.usage);
  const billing = value.billing === undefined ? undefined : parseBilling(value.billing);
  if (
    (value.usage !== undefined && usage === undefined) ||
    (value.billing !== undefined && billing === undefined)
  )
    return undefined;
  return {
    mimeType: value.mimeType,
    extension: value.extension,
    createdAt: value.createdAt,
    ...(usage === undefined ? {} : { usage }),
    ...(billing === undefined ? {} : { billing }),
  };
}

function parseUsage(value: unknown): AssetUsage | undefined {
  if (!isRecord(value) || !hasAllowedKeys(value, ["inputUnits", "outputUnits"])) return undefined;
  const inputUnits = value.inputUnits;
  const outputUnits = value.outputUnits;
  if (
    (inputUnits !== undefined &&
      (typeof inputUnits !== "number" || !Number.isSafeInteger(inputUnits) || inputUnits < 0)) ||
    (outputUnits !== undefined &&
      (typeof outputUnits !== "number" || !Number.isSafeInteger(outputUnits) || outputUnits < 0))
  ) {
    return undefined;
  }
  return {
    ...(typeof inputUnits === "number" ? { inputUnits } : {}),
    ...(typeof outputUnits === "number" ? { outputUnits } : {}),
  };
}

function parseBilling(value: unknown): AssetBilling | undefined {
  if (
    !isRecord(value) ||
    !hasAllowedKeys(value, ["chargeStatus", "cost"]) ||
    (value.chargeStatus !== "not-charged" &&
      value.chargeStatus !== "charged" &&
      value.chargeStatus !== "unknown")
  ) {
    return undefined;
  }
  const cost = value.cost === undefined ? undefined : parseCost(value.cost);
  if (value.cost !== undefined && cost === undefined) return undefined;
  return { chargeStatus: value.chargeStatus, ...(cost === undefined ? {} : { cost }) };
}

function parseCost(value: unknown): AssetCost | undefined {
  if (!isRecord(value) || typeof value.kind !== "string") return undefined;
  if (value.kind === "unavailable") return hasOnlyKeys(value, ["kind"]) ? { kind: "unavailable" } : undefined;
  if (
    typeof value.amount !== "number" ||
    !Number.isFinite(value.amount) ||
    value.amount < 0 ||
    typeof value.currency !== "string" ||
    !/^[A-Z]{3}$/.test(value.currency)
  ) {
    return undefined;
  }
  if (value.kind === "reported") {
    return hasOnlyKeys(value, ["kind", "amount", "currency"])
      ? { kind: "reported", amount: value.amount, currency: value.currency }
      : undefined;
  }
  if (value.kind === "estimated") {
    return hasOnlyKeys(value, ["kind", "amount", "currency", "basis"]) &&
      typeof value.basis === "string" &&
      value.basis.length > 0
      ? { kind: "estimated", amount: value.amount, currency: value.currency, basis: value.basis }
      : undefined;
  }
  return undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(record: Record<string, unknown>, keys: readonly string[]): boolean {
  const actual = Object.keys(record);
  return actual.length === keys.length && actual.every((key) => keys.includes(key));
}

function hasAllowedKeys(record: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(record).every((key) => keys.includes(key));
}

function safeId(value: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(value);
}

function safeModel(value: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/.test(value);
}

function safeRelativePath(value: string): boolean {
  if (!value || value.includes("\\") || value.includes("\u0000") || value.startsWith("/")) return false;
  return value
    .split("/")
    .every((part) => /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(part) && part !== "." && part !== "..");
}
