import {
  assertOpenRouterRequestSupported,
  classifyAssetError,
  hashAssetPrompt,
  hashAssetRequest,
  openAiAssetProvider,
  openRouterAssetProvider,
  resolveAssetTarget,
  selectAssetPostProcessingRecipe,
  redactResolvedAssetRequest,
} from "@ludelier/assets";
import type {
  AssetGenerationMetadata,
  AssetGenerationRequest,
  AssetGenerationResult,
  AssetProvider,
  AssetRole,
  ResolvedAssetGenerationRequest,
  AssetProvenanceTarget,
  RedactedAssetRequest,
} from "@ludelier/assets";

declare global {
  interface ImportMeta {
    readonly env: { readonly DEV: boolean };
  }
}

export const ASSET_PREFLIGHT_ENDPOINT = "/__ludelier/assets/preflight";
export const ASSET_PERSIST_ENDPOINT = "/__ludelier/assets/persist";

export type AssetProviderChoice = "openai" | "openrouter";
export type AssetHostMode = "dev" | "static";

/**
 * All editable, non-secret values required to make one asset. The prompt remains only in React
 * state and the provider call; it is never part of an outcome, Story command, or host response.
 */
export interface AssetDraft {
  readonly storyId: string;
  readonly provider: AssetProviderChoice;
  readonly model: string;
  readonly kind: "image" | "audio";
  readonly role: AssetRole;
  readonly prompt: string;
  readonly assetId: string;
  readonly destination: string;
}

/** Kept in component memory; callers must not persist this value. */
export interface AssetAuthorization {
  readonly apiKey: string;
  readonly approved: boolean;
}

export interface AssetGenerationInput extends AssetDraft, AssetAuthorization {}

/** Prompt- and key-free data accepted before any chargeable provider dispatch. */
export interface SafeAssetPreflightPayload {
  readonly destination: {
    readonly storyId: string;
    readonly assetId: string;
    readonly relativePath: string;
  };
  readonly target: AssetProvenanceTarget;
  readonly request: RedactedAssetRequest;
  readonly requestHash: string;
  readonly promptHash: string;
}

/** The one-use receipt and generated bytes accepted only after a successful preflight. */
export interface SafeAssetPersistencePayload {
  readonly receipt: string;
  readonly metadata: Pick<
    AssetGenerationMetadata,
    "mimeType" | "extension" | "createdAt" | "usage" | "billing"
  >;
  readonly bytes: Uint8Array;
}

/** Redacted data returned by the development persistence endpoint. */
export interface PersistedAsset {
  readonly assetId: string;
  readonly publicUrl: string;
  readonly kind: "image" | "audio";
  readonly mimeType: string;
  readonly extension: string;
  readonly byteSize: number;
}

export type AssetPreflightResult =
  | { readonly status: "cache-hit"; readonly asset: PersistedAsset }
  | { readonly status: "ready"; readonly receipt: string };

export interface AssetPersistence {
  preflight(payload: SafeAssetPreflightPayload, signal?: AbortSignal): Promise<AssetPreflightResult>;
  persist(payload: SafeAssetPersistencePayload, signal?: AbortSignal): Promise<PersistedAsset>;
}

export interface AssetHostFailure {
  readonly code: string;
  readonly message: string;
  readonly mayHaveCharged: boolean;
}

/**
 * A successful outcome keeps only an object URL. The Blob is retained in the closure used for a
 * gesture-driven download and is never exposed to Story, chat, or callers' serialized state.
 * A verified server-side cache hit uses its public URL instead and retains no bytes locally.
 */
export interface PreviewAssetOutcome {
  readonly success: true;
  readonly mode: "preview";
  readonly previewUrl: string;
  readonly mimeType: string;
  readonly extension: string;
  readonly assetId: string;
  download(): void;
}

export interface PersistedAssetOutcome {
  readonly success: true;
  readonly mode: "persisted";
  readonly previewUrl: string;
  readonly asset: PersistedAsset;
}

export interface FailedAssetOutcome {
  readonly success: false;
  readonly error: AssetHostFailure;
}

export type AssetHostOutcome = PreviewAssetOutcome | PersistedAssetOutcome | FailedAssetOutcome;

export interface AssetGenerationHost {
  readonly mode: AssetHostMode;
  readonly ready: boolean;
  generate(input: AssetGenerationInput, signal?: AbortSignal): Promise<AssetHostOutcome>;
  release(outcome: AssetHostOutcome): void;
  dispose(): void;
}

export interface BrowserAssetHostOptions {
  /** A persistence adapter exists only in Vite development. Omitting it creates a static host. */
  readonly persistence?: AssetPersistence;
  /** Injectable seam keeps unit tests hermetic and prevents a provider from being constructed early. */
  readonly createProviders?: (input: AssetGenerationInput) => Promise<readonly AssetProvider[]>;
  readonly createObjectUrl?: (blob: Blob) => string;
  readonly revokeObjectUrl?: (url: string) => void;
}

/**
 * The one browser generation path used by the inspector and the authorized agent tool. It
 * completes a prompt-free server preflight before dispatching a chargeable vendor request.
 */
export function createBrowserAssetHost(options: BrowserAssetHostOptions = {}): AssetGenerationHost {
  const persistence = options.persistence;
  const createProviders = options.createProviders ?? createPortableProviders;
  const createObjectUrl = options.createObjectUrl ?? ((blob: Blob) => URL.createObjectURL(blob));
  const revokeObjectUrl = options.revokeObjectUrl ?? ((url: string) => URL.revokeObjectURL(url));
  const liveUrls = new Set<string>();

  return {
    mode: persistence === undefined ? "static" : "dev",
    ready: persistence !== undefined,
    async generate(input, signal) {
      if (!input.approved)
        return failure("approval-required", "Enable paid generation before requesting an asset.", false);
      if (!input.apiKey.trim())
        return failure("key-required", "Paste a provider API key before requesting an asset.", false);

      let request: AssetGenerationRequest;
      try {
        request = requestFromDraft(input);
        assertOpenRouterRequestSupported(request);
      } catch (error) {
        return safeFailure(error);
      }

      let resolved: ResolvedAssetGenerationRequest;
      let provider: AssetProvider;
      let receipt: string | undefined;
      try {
        const providers = await createProviders(input);
        resolved = resolveAssetTarget(providers, request);
        const selectedProvider = providers.find((candidate) => candidate.id === resolved.target.providerId);
        if (selectedProvider === undefined)
          return failure("provider-unavailable", "Selected asset provider is unavailable.", false);
        provider = selectedProvider;

        if (persistence !== undefined) {
          const recipe = selectAssetPostProcessingRecipe(resolved);
          const [requestHash, promptHash] = await Promise.all([
            hashAssetRequest(resolved, recipe),
            hashAssetPrompt(request.prompt),
          ]);
          const preflight = await persistence.preflight(
            {
              destination: {
                storyId: input.storyId,
                assetId: input.assetId,
                relativePath: input.destination,
              },
              target: {
                providerId: resolved.target.providerId,
                modelId: resolved.target.modelId,
                kind: resolved.target.kind,
                endpoint: resolved.target.endpoint,
              },
              request: redactResolvedAssetRequest(resolved),
              requestHash,
              promptHash,
            },
            signal,
          );
          if (preflight.status === "cache-hit") {
            if (!matchesDestination(preflight.asset, input))
              return failure(
                "invalid-request",
                "Check the asset id, destination, role, model, and prompt.",
                false,
              );
            return {
              success: true,
              mode: "persisted",
              previewUrl: preflight.asset.publicUrl,
              asset: preflight.asset,
            };
          }
          receipt = preflight.receipt;
        }
      } catch (error) {
        return safeFailure(error);
      }

      let generated: AssetGenerationResult;
      try {
        generated = await provider.generate(resolved, { signal });
      } catch (error) {
        return safeFailure(error);
      }

      const previewUrl = createObjectUrl(
        new Blob([blobBytes(generated.bytes)], { type: generated.mimeType }),
      );
      liveUrls.add(previewUrl);

      if (persistence === undefined) {
        return {
          success: true,
          mode: "preview",
          previewUrl,
          mimeType: generated.mimeType,
          extension: generated.extension,
          assetId: input.assetId,
          download: () => downloadBlob(previewUrl, safeDownloadName(input.assetId, generated.extension)),
        };
      }

      try {
        if (receipt === undefined) throw new AssetIngressError("invalid-request", false, "persistence");
        const asset = await persistence.persist(
          {
            receipt,
            metadata: safeGenerationMetadata(generated),
            bytes: generated.bytes,
          },
          signal,
        );
        if (!matchesDestination(asset, input)) throw new Error("invalid-request");
        return { success: true, mode: "persisted", previewUrl, asset };
      } catch (error) {
        revokeObjectUrl(previewUrl);
        liveUrls.delete(previewUrl);
        // The provider returned successfully. Even a later receipt/write error cannot honestly
        // promise that the vendor did not bill this request.
        return safeFailure(error, true);
      }
    },
    release(outcome) {
      if (!outcome.success || !liveUrls.delete(outcome.previewUrl)) return;
      revokeObjectUrl(outcome.previewUrl);
    },
    dispose() {
      for (const url of liveUrls) revokeObjectUrl(url);
      liveUrls.clear();
    },
  };
}

/** Vite-only adapter. Static builds never call it and all URLs are same-origin and fixed. */
export function createDevAssetPersistence(fetchImpl: typeof fetch = fetch): AssetPersistence {
  return {
    async preflight(payload, signal) {
      const response = await fetchImpl(ASSET_PREFLIGHT_ENDPOINT, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(payload),
        signal,
      });
      const parsed: unknown = await response.json().catch(() => undefined);
      if (!response.ok) throw ingressError(parsed, "preflight");
      const result = parsePreflightResult(parsed);
      if (result === undefined) throw new AssetIngressError("persistence-failed", false, "preflight");
      return result;
    },
    async persist(payload, signal) {
      const response = await fetchImpl(ASSET_PERSIST_ENDPOINT, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          receipt: payload.receipt,
          metadata: payload.metadata,
          bytesBase64: bytesToBase64(payload.bytes),
        }),
        signal,
      });
      const parsed: unknown = await response.json().catch(() => undefined);
      if (!response.ok) throw ingressError(parsed, "persistence");
      const asset = parsePersistedAsset(parsed);
      if (asset === undefined) throw new AssetIngressError("persistence-failed", true, "persistence");
      return asset;
    },
  };
}

/** Build a static-safe or Vite-development host without importing any Node-only module. */
export function createDefaultAssetHost(): AssetGenerationHost {
  return createBrowserAssetHost({
    persistence: import.meta.env.DEV ? createDevAssetPersistence() : undefined,
  });
}

/** Provider creation is deliberately private to an invocation after approval, never a component effect. */
async function createPortableProviders(input: AssetGenerationInput): Promise<readonly AssetProvider[]> {
  const apiKey = input.apiKey.trim();
  if (input.provider === "openai") {
    return [
      openAiAssetProvider({
        apiKey,
        fetchImpl: fetch,
        ...(input.kind === "image" ? { imageModel: input.model } : { speechModel: input.model }),
      }),
    ];
  }
  return [
    await openRouterAssetProvider({
      apiKey,
      fetchImpl: fetch,
      discoveryFetchImpl: fetch,
      appName: "Ludelier Editor",
      appUrl: location.origin,
    }),
  ];
}

function requestFromDraft(input: AssetDraft): AssetGenerationRequest {
  if (!safeId(input.storyId) || !safeId(input.assetId) || !safeRelativePath(input.destination)) {
    throw new Error("invalid-request");
  }
  if (!input.prompt.trim() || !safeModel(input.model)) throw new Error("invalid-request");

  if (input.kind === "image") {
    if ((input.role !== "background" && input.role !== "sprite") || !input.destination.endsWith(".png")) {
      throw new Error("invalid-request");
    }
    return {
      kind: "image",
      prompt: input.prompt,
      role: input.role,
      outputFormat: "png",
      providerId: input.provider,
      modelId: input.model,
    };
  }
  if (
    (input.role !== "music" && input.role !== "sfx" && input.role !== "voice") ||
    !input.destination.endsWith(".mp3")
  ) {
    throw new Error("invalid-request");
  }
  return {
    kind: "audio",
    prompt: input.prompt,
    role: input.role,
    outputFormat: "mp3",
    providerId: input.provider,
    modelId: input.model,
  };
}

function safeGenerationMetadata(generated: AssetGenerationResult): SafeAssetPersistencePayload["metadata"] {
  return {
    mimeType: generated.mimeType,
    extension: generated.extension,
    createdAt: generated.createdAt,
    ...(generated.usage === undefined ? {} : { usage: generated.usage }),
    ...(generated.billing === undefined ? {} : { billing: generated.billing }),
  };
}

function matchesDestination(asset: PersistedAsset, input: AssetGenerationInput): boolean {
  return (
    asset.assetId === input.assetId &&
    asset.kind === input.kind &&
    asset.publicUrl === `/assets/${input.storyId}/${input.destination}`
  );
}

function parsePreflightResult(value: unknown): AssetPreflightResult | undefined {
  if (!isRecord(value) || typeof value.status !== "string") return undefined;
  if (value.status === "cache-hit" && hasOnlyKeys(value, ["status", "asset"])) {
    const asset = parsePersistedAsset({ asset: value.asset });
    return asset === undefined ? undefined : { status: "cache-hit", asset };
  }
  if (
    value.status === "ready" &&
    hasOnlyKeys(value, ["status", "receipt"]) &&
    typeof value.receipt === "string" &&
    /^[A-Za-z0-9_-]{24,128}$/.test(value.receipt)
  ) {
    return { status: "ready", receipt: value.receipt };
  }
  return undefined;
}

function parsePersistedAsset(value: unknown): PersistedAsset | undefined {
  if (!isRecord(value) || !isRecord(value.asset)) return undefined;
  const asset = value.asset;
  if (
    typeof asset.assetId !== "string" ||
    !safeId(asset.assetId) ||
    typeof asset.publicUrl !== "string" ||
    !isRootAssetUrl(asset.publicUrl) ||
    (asset.kind !== "image" && asset.kind !== "audio") ||
    typeof asset.mimeType !== "string" ||
    typeof asset.extension !== "string" ||
    !/^[a-z0-9]+$/.test(asset.extension) ||
    typeof asset.byteSize !== "number" ||
    !Number.isSafeInteger(asset.byteSize) ||
    asset.byteSize < 1
  ) {
    return undefined;
  }
  return {
    assetId: asset.assetId,
    publicUrl: asset.publicUrl,
    kind: asset.kind,
    mimeType: asset.mimeType,
    extension: asset.extension,
    byteSize: asset.byteSize,
  };
}

class AssetIngressError extends Error {
  constructor(
    readonly code: string,
    readonly mayHaveCharged: boolean,
    readonly phase: "preflight" | "persistence",
  ) {
    super("Asset ingress failed.");
    this.name = "AssetIngressError";
  }
}

function ingressError(value: unknown, phase: "preflight" | "persistence"): AssetIngressError {
  if (
    isRecord(value) &&
    isRecord(value.error) &&
    typeof value.error.code === "string" &&
    typeof value.error.mayHaveCharged === "boolean"
  ) {
    return new AssetIngressError(value.error.code, value.error.mayHaveCharged, phase);
  }
  return new AssetIngressError("persistence-failed", phase === "persistence", phase);
}

function failure(code: string, message: string, mayHaveCharged: boolean): FailedAssetOutcome {
  return { success: false, error: { code, message, mayHaveCharged } };
}

function safeFailure(error: unknown, mayHaveChargedFloor = false): FailedAssetOutcome {
  if (error instanceof AssetIngressError) {
    const message =
      error.code === "destination-conflict"
        ? "The selected destination is already occupied by another asset."
        : error.code === "reservation-busy"
          ? "This asset destination is already being generated."
          : error.phase === "preflight"
            ? "Asset preflight failed."
            : "Asset persistence failed.";
    return failure(error.code, message, error.mayHaveCharged || mayHaveChargedFloor);
  }
  if (error instanceof Error && error.message === "invalid-request") {
    return failure(
      "invalid-request",
      "Check the asset id, destination, role, model, and prompt.",
      mayHaveChargedFloor,
    );
  }
  const redacted = classifyAssetError(error);
  return failure(redacted.code, redacted.message, redacted.mayHaveCharged || mayHaveChargedFloor);
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = "";
  const chunkSize = 0x8000;
  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize));
  }
  return btoa(binary);
}

function blobBytes(bytes: Uint8Array): Uint8Array<ArrayBuffer> {
  if (bytes.buffer instanceof ArrayBuffer) {
    return new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  }
  // Shared buffers cannot back a BlobPart in TypeScript's DOM definitions; copy only then.
  return new Uint8Array(bytes);
}

function downloadBlob(url: string, filename: string): void {
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
}

function safeDownloadName(assetId: string, extension: string): string {
  return `${assetId.replace(/[^A-Za-z0-9_-]/g, "-") || "asset"}.${extension}`;
}

function safeId(value: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(value);
}

function safeModel(value: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/.test(value);
}

function safeRelativePath(value: string): boolean {
  if (!value || value.includes("\\") || value.includes("\u0000") || value.startsWith("/")) return false;
  return value
    .split("/")
    .every((part) => /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(part) && part !== "." && part !== "..");
}

function isRootAssetUrl(value: unknown): value is string {
  return (
    typeof value === "string" &&
    /^\/assets\/[A-Za-z0-9][A-Za-z0-9_-]{0,127}\/[A-Za-z0-9][A-Za-z0-9._/-]*$/.test(value) &&
    !value.includes("//") &&
    !value.includes("..") &&
    !value.includes("\\")
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(record: Record<string, unknown>, keys: readonly string[]): boolean {
  const actual = Object.keys(record);
  return actual.length === keys.length && actual.every((key) => keys.includes(key));
}
