import { Buffer } from "node:buffer";
import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { fileURLToPath } from "node:url";
// The @ludelier/assets-node package is source-only TypeScript. Load it through tsx so its
// extensionless workspace imports stay in the Vite config's Node-only boundary.
import { tsImport } from "tsx/esm/api";
import type { AssetNodePersistedAsset, BrowserGeneratedAssetReadyPreflight } from "@ludelier/assets-node";
import {
  MAX_ASSET_INGRESS_BYTES,
  MAX_ASSET_INGRESS_JSON_BYTES,
  parseBrowserAssetPersistPayload,
  parseBrowserAssetPreflightPayload,
} from "./src/assets/ingress";
import type { BrowserAssetPersistPayload, BrowserAssetPreflightPayload } from "./src/assets/ingress";
import { defineConfig } from "vite";
import type { Plugin } from "vite";
import react from "@vitejs/plugin-react";

const { AssetNodeStore, persistBrowserGeneratedAsset, preflightBrowserGeneratedAsset } = await tsImport(
  "@ludelier/assets-node",
  import.meta.url,
);

// Workspace root — lets the dev server read the shared examples/ + workspace packages.
const workspaceRoot = fileURLToPath(new URL("../../", import.meta.url));
// Reuse the runtime-web player's committed assets (/assets/<story>/…) for the play preview.
const sharedPublic = fileURLToPath(new URL("../runtime-web/public", import.meta.url));
const assetPublicRoot = fileURLToPath(new URL("../runtime-web/public/assets", import.meta.url));
// This root is deliberately outside Vite's public directory and denied explicitly through /@fs/.
const assetProvenanceRoot = fileURLToPath(new URL("../runtime-web/.asset-provenance", import.meta.url));
const assetPreflightPath = "/__ludelier/assets/preflight";
const assetPersistPath = "/__ludelier/assets/persist";
const maxJsonBytes = MAX_ASSET_INGRESS_JSON_BYTES;
const maxAssetBytes = MAX_ASSET_INGRESS_BYTES;
const defaultReceiptTtlMs = 2 * 60 * 1000;
/** Vite replaces this list rather than merging it, so retain its sensitive-file defaults. */
export const assetProvenanceFsDeny: string[] = [
  ".env",
  ".env.*",
  "*.{crt,pem}",
  "**/.git/**",
  "**/.asset-provenance/**",
];

type BrowserAssetPayload = Omit<BrowserAssetPersistPayload, "bytesBase64"> & {
  readonly bytes: Uint8Array;
};

interface ServerReceipt {
  readonly preflight: BrowserGeneratedAssetReadyPreflight;
  readonly destinationKey: string;
  readonly expiresAt: number;
}

interface AssetPersistenceOptions {
  readonly publicRoot?: string;
  readonly provenanceRoot?: string;
  readonly receiptTtlMs?: number;
  /** Injectable clock keeps expiry behavior deterministic in real-middleware request tests. */
  readonly now?: () => number;
}

/**
 * Development-only ingress for browser-generated bytes. A prompt-free preflight reserves a
 * destination before vendor dispatch, retains the assets-node capability object only on the
 * server, and returns an expiring one-use opaque receipt for persistence.
 */
export function editorAssetPersistence(options: AssetPersistenceOptions = {}): Plugin {
  const store = new AssetNodeStore({
    publicRoot: options.publicRoot ?? assetPublicRoot,
    provenanceRoot: options.provenanceRoot ?? assetProvenanceRoot,
  });
  const receiptTtlMs = options.receiptTtlMs ?? defaultReceiptTtlMs;
  const now = options.now ?? Date.now;
  const receipts = new Map<string, ServerReceipt>();
  // `null` is an in-progress preflight; a receipt string holds the reservation until persist or TTL.
  const reservations = new Map<string, string | null>();

  function releaseReceipt(receipt: string): void {
    const held = receipts.get(receipt);
    if (held === undefined) return;
    receipts.delete(receipt);
    if (reservations.get(held.destinationKey) === receipt) reservations.delete(held.destinationKey);
  }

  function destinationReserved(destinationKey: string): boolean {
    const receipt = reservations.get(destinationKey);
    if (receipt === undefined) return false;
    if (receipt !== null) {
      const held = receipts.get(receipt);
      if (held === undefined || held.expiresAt <= now()) {
        releaseReceipt(receipt);
        return reservations.has(destinationKey);
      }
    }
    return true;
  }

  function takeReceipt(receipt: string): ServerReceipt | undefined {
    const held = receipts.get(receipt);
    if (held === undefined || held.expiresAt <= now()) {
      if (held !== undefined) releaseReceipt(receipt);
      return undefined;
    }
    if (reservations.get(held.destinationKey) !== receipt) return undefined;
    // Consume before processing bytes: every valid persistence attempt is one-use, regardless of
    // whether local processing succeeds after a provider may have charged.
    receipts.delete(receipt);
    return held;
  }

  return {
    name: "ludelier-editor-asset-persistence",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const pathname = request.url?.split("?", 1)[0];
        if (pathname === assetPreflightPath) {
          void preflight(request, response);
          return;
        }
        if (pathname === assetPersistPath) {
          void persist(request, response);
          return;
        }
        next();
      });
    },
  };

  async function preflight(request: IncomingMessage, response: ServerResponse): Promise<void> {
    if (!isJsonPost(request, response)) return;
    try {
      const payload = parseBrowserAssetPreflightPayload(await readJson(request));
      if (payload === undefined) {
        sendFailure(response, 400, "invalid-request", false);
        return;
      }
      const destinationKey = reservationKey(payload);
      if (destinationReserved(destinationKey)) {
        sendFailure(response, 409, "reservation-busy", false, true);
        return;
      }
      reservations.set(destinationKey, null);
      try {
        const result = await preflightBrowserGeneratedAsset({
          store,
          target: payload.target,
          request: payload.request,
          requestHash: payload.requestHash,
          promptHash: payload.promptHash,
          destination: payload.destination,
        });
        if (result.status === "failed") {
          reservations.delete(destinationKey);
          sendFailure(
            response,
            result.failure.code === "destination-conflict" ? 409 : 400,
            result.failure.code,
            false,
            result.failure.retryable,
          );
          return;
        }
        if (result.status === "cache-hit") {
          reservations.delete(destinationKey);
          sendJson(response, 200, { status: "cache-hit", asset: publicAsset(result.asset) });
          return;
        }

        const receipt = randomUUID().replaceAll("-", "");
        receipts.set(receipt, {
          preflight: result.preflight,
          destinationKey,
          expiresAt: now() + receiptTtlMs,
        });
        reservations.set(destinationKey, receipt);
        const expiration = setTimeout(() => releaseReceipt(receipt), receiptTtlMs);
        expiration.unref?.();
        sendJson(response, 200, { status: "ready", receipt });
      } catch {
        reservations.delete(destinationKey);
        throw new Error("preflight-failed");
      }
    } catch {
      // Parsing and all unclassified Node failures are deliberately normalized at this boundary.
      sendFailure(response, 400, "invalid-request", false);
    }
  }

  async function persist(request: IncomingMessage, response: ServerResponse): Promise<void> {
    if (!isJsonPost(request, response)) return;
    try {
      const payload = parseBrowserAssetPayload(await readJson(request));
      if (payload === undefined) {
        sendFailure(response, 400, "invalid-request", false);
        return;
      }
      const held = takeReceipt(payload.receipt);
      if (held === undefined) {
        sendFailure(response, 410, "invalid-receipt", false);
        return;
      }
      try {
        const persisted = await persistBrowserGeneratedAsset({
          preflight: held.preflight,
          bytes: payload.bytes,
          metadata: payload.metadata,
        });
        if (persisted.status === "failed") {
          sendFailure(
            response,
            persisted.failure.code === "destination-conflict" ? 409 : 422,
            persisted.failure.code,
            persisted.failure.mayHaveCharged,
            persisted.failure.retryable,
          );
          return;
        }
        sendJson(response, 200, { asset: publicAsset(persisted.asset) });
      } finally {
        if (reservations.get(held.destinationKey) === payload.receipt) {
          reservations.delete(held.destinationKey);
        }
      }
    } catch {
      // Parsing and all unclassified Node failures are deliberately normalized at this boundary.
      sendFailure(response, 400, "invalid-request", false);
    }
  }
}

export function parseBrowserAssetPayload(value: unknown): BrowserAssetPayload | undefined {
  const parsed = parseBrowserAssetPersistPayload(value);
  if (parsed === undefined) return undefined;

  const bytes = Buffer.from(parsed.bytesBase64, "base64");
  if (bytes.byteLength === 0 || bytes.byteLength > maxAssetBytes) return undefined;

  const { bytesBase64: _bytesBase64, ...payload } = parsed;
  return { ...payload, bytes };
}

function reservationKey(payload: BrowserAssetPreflightPayload): string {
  // The same relative media path is one physical destination regardless of the Story-facing id.
  return `${payload.destination.storyId}\u0000${payload.destination.relativePath}`;
}

function isJsonPost(request: IncomingMessage, response: ServerResponse): boolean {
  if (request.method !== "POST") {
    sendFailure(response, 405, "method-not-allowed", false);
    return false;
  }
  if (!request.headers["content-type"]?.toLowerCase().startsWith("application/json")) {
    sendFailure(response, 415, "invalid-request", false);
    return false;
  }
  return true;
}

function publicAsset(asset: AssetNodePersistedAsset): {
  readonly assetId: string;
  readonly publicUrl: string;
  readonly kind: "image" | "audio";
  readonly mimeType: string;
  readonly extension: string;
  readonly byteSize: number;
} {
  return {
    assetId: asset.assetId,
    publicUrl: asset.publicUrl,
    kind: asset.provenance.target.kind,
    mimeType: asset.mimeType,
    extension: asset.extension,
    byteSize: asset.byteSize,
  };
}

async function readJson(request: IncomingMessage): Promise<unknown> {
  const declaredLength = Number(request.headers["content-length"] ?? 0);
  if (!Number.isSafeInteger(declaredLength) || declaredLength < 1 || declaredLength > maxJsonBytes)
    throw new Error();
  const chunks: Buffer[] = [];
  let length = 0;
  for await (const chunk of request) {
    const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
    length += bytes.byteLength;
    if (length > maxJsonBytes) throw new Error();
    chunks.push(bytes);
  }
  return JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown;
}

function sendFailure(
  response: ServerResponse,
  status: number,
  code: string,
  mayHaveCharged: boolean,
  retryable = false,
): void {
  sendJson(response, status, { error: { code, retryable, mayHaveCharged } });
}

function sendJson(response: ServerResponse, status: number, body: unknown): void {
  response.statusCode = status;
  response.setHeader("content-type", "application/json; charset=utf-8");
  response.setHeader("cache-control", "no-store");
  response.end(JSON.stringify(body));
}

export default defineConfig({
  publicDir: sharedPublic,
  server: {
    fs: {
      allow: [workspaceRoot],
      deny: assetProvenanceFsDeny,
    },
  },
  build: { target: "es2022" },
  plugins: [react(), editorAssetPersistence()],
});
